# Generated by Django 4.1.2 on 2022-10-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todoapp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("DELETED", "Deleted"),
                        ],
                        default="PENDING",
                        max_length=25,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("BLACK", "Black"),
                            ("BLUE", "Blue"),
                            ("RED", "Red"),
                            ("YELLOW", "Yellow"),
                            ("GREEN", "Green"),
                        ],
                        default="BLACK",
                        max_length=15,
                    ),
                ),
                ("Is_important", models.BooleanField()),
            ],
        ),
    ]
