# Generated by Django 4.1.2 on 2022-10-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_is_important_todoapp_is_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoapp",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="todoapp",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
    ]
