# Generated by Django 4.1.2 on 2022-10-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_todoapp_created_alter_todoapp_is_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoapp",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="todoapp", name="created", field=models.DateTimeField(),
        ),
    ]
