# Generated by Django 4.1.2 on 2022-10-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_todoapp_updated_alter_todoapp_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoapp",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
