# Generated by Django 4.1.2 on 2022-11-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_todoapp_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapp',
            old_name='userId',
            new_name='user_id',
        ),
    ]
